### ISSUE TITLE
跟ClingService投屏服务冲突，无法同时开启

### ISSUE THREAD

**Issue by hiliving** [yangchong211/YCUpdateApp#2]
我的项目里引入了Cling投屏库，在application里需要初始化，但是会跟版本更新库的初始化冲突，无法下载文件：

日志如下：
2019-03-29 15:15:11.861 20077-20077/dev.baofeng.com.supermovie:filedownloader E/AndroidRuntime: FATAL EXCEPTION: main
    Process: dev.baofeng.com.supermovie:filedownloader, PID: 20077
    java.lang.ClassCastException: android.os.BinderProxy cannot be cast to com.yanbo.lib_screen.service.ClingService$LocalBinder
        at com.yanbo.lib_screen.manager.ClingManager$1.onServiceConnected(ClingManager.java:129)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1496)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1524)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:177)
        at android.app.ActivityThread.main(ActivityThread.java:6691)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
2019-03-29 15:15:13.055 20180-20180/dev.baofeng.com.supermovie:filedownloader E/CrashHandler: In thread: Thread[main,5,main]
    UncaughtException detected: java.lang.ClassCastException: android.os.BinderProxy cannot be cast to com.yanbo.lib_screen.service.ClingService$LocalBinder
        at com.yanbo.lib_screen.manager.ClingManager$1.onServiceConnected(ClingManager.java:129)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1496)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1524)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:177)
        at android.app.ActivityThread.main(ActivityThread.java:6691)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
2019-03-29 15:15:13.176 20180-20180/dev.baofeng.com.supermovie:filedownloader E/AndroidRuntime: FATAL EXCEPTION: main
    Process: dev.baofeng.com.supermovie:filedownloader, PID: 20180
    java.lang.ClassCastException: android.os.BinderProxy cannot be cast to com.yanbo.lib_screen.service.ClingService$LocalBinder
        at com.yanbo.lib_screen.manager.ClingManager$1.onServiceConnected(ClingManager.java:129)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1496)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1524)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:177)
        at android.app.ActivityThread.main(ActivityThread.java:6691)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
2019-03-29 15:15:14.366 20272-20272/dev.baofeng.com.supermovie:filedownloader E/CrashHandler: In thread: Thread[main,5,main]
    UncaughtException detected: java.lang.ClassCastException: android.os.BinderProxy cannot be cast to com.yanbo.lib_screen.service.ClingService$LocalBinder
        at com.yanbo.lib_screen.manager.ClingManager$1.onServiceConnected(ClingManager.java:129)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1496)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1524)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:177)
        at android.app.ActivityThread.main(ActivityThread.java:6691)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)

进入Cling服务中指向的位置：代码如下：看下是否有问题：
 private void bindService() {
        this.clingServiceConnection = new ServiceConnection() {
            public void onServiceConnected(ComponentName name, IBinder service) {
                LogUtils.i("onServiceConnected - %s", name);
                LocalBinder binder = (LocalBinder)service;
                ClingService clingService = binder.getService();
                ClingManager.this.setClingService(clingService);
                ClingManager.this.clingRegistryListener = new ClingRegistryListener();
                ClingManager.this.getRegistry().addListener(ClingManager.this.clingRegistryListener);
                ClingManager.this.searchDevices();
                ClingManager.this.searchLocalContent("0");
            }

            public void onServiceDisconnected(ComponentName name) {
                LogUtils.e("onServiceDisconnected - %s", name);
                ClingManager.this.setClingService((ClingService)null);
            }
        };

**Comment by jinji-hanbin** [comment]
@hiliving 找到解决办法了吗？
